In [2]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import math
import re

import sys
sys.path.append('../../..')
from mount_drive import mount_s_drive

In [8]:
mount_s_drive(subfolder='LCICM/Databases/ACCMPMAP')

Password for ikarhul1: ········

Mounting S drive subfolder LCICM/Databases/ACCMPMAP

mkdir: cannot create directory '/home/idies/workspace/SAFE/': File exists

The following files and folders have been mounted to /home/idies/workspace/SAFE/:
  SAFE
  2022-03-16
  Flowsheet2.csv
  Flowsheet_osler_ids.xlsx
  Sickbay
  ptsd_signal
  2021-12-16
  core_icustay_8_15_2024.csv
  DID
  flow_craniotomy.csv
  Flowsheet9.csv
  Flowsheet5.csv
  Flowsheet11.csv
  Flowsheet1.csv
  Flowsheet4.csv
  Flowsheet10.csv
  Flowsheet8.csv
  old
  core.info_stay_mv.csv
  2021-09-27
  Flowsheet3.csv
  2021-09-21
  RadiologyReports
  Untitled.ipynb
  2024-04-22
  dbo.accm_flowsheet.csv
  2024-04-29
  Flowsheet6.csv
  2024-08-15
  2024-06-29
  Flowsheet7.csv

In [9]:
data_dir = '/home/idies/workspace/SAFE/'

In [10]:
def read_by_chunks(file_path,chunk_size=1e6,head='infer'):
    df_chunks = []
    num_chunks = 0
    
    for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
        #chunk = chunk[chunk[0].isin(patient_ids)]
        df_chunks.append(chunk)
        if num_chunks % 20 == 0:
            print(f'Chunk {num_chunks} Processed.')
        num_chunks += 1
        del chunk
    print('Processing finished.')
    
    return pd.concat(df_chunks, ignore_index=True)

In [11]:
def nameSearchCardiacArrest(text):
    text = str(text).lower()
    patterns = [r'cardia.*rrest',
                r'cardio.*rrest',
                r'circulat.*rrest',
                r'\basystole',
                r'\basystolia',
                r'\bpea\b|pulseless elec.*act.*']
    if any(re.search(pattern, text) for pattern in patterns):
        exclusion_patterns = [r'history|hx|h/o',
                              r'before cardiac arrest',
                              r'due to cardiac arrest',
                              r'neonatal',
                              r'newborn']       
        if not any(re.search(pattern, text) for pattern in exclusion_patterns):
            return True   
    return False

def icdSearchCardiacArrest(text):
    text = str(text).lower()
    icd10_match = re.search(r'\bi46\.\b', text)
    icd9_match = re.search(r'\b427\.5\b', text)
    return bool(icd10_match or icd9_match)

In [12]:
patients_df = pd.read_csv(data_dir+'2024-08-15/dbo.accm_patient.csv')
inpatient_df = read_by_chunks(data_dir+'2024-08-15/dbo.accm_inpatient.csv')
icustay_df = pd.read_csv(data_dir+'core_icustay_8_15_2024.csv')
encounter_dx_df = read_by_chunks(data_dir+'2024-08-15/dbo.accm_encounter_dx.csv')

/tmp/ipykernel_188/3469504997.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  patients_df = pd.read_csv(data_dir+'2024-08-15/dbo.accm_patient.csv')

Chunk 0 Processed.
Processing finished.

/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):

Chunk 0 Processed.

/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):

Chunk 20 Processed.

/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):

Chunk 40 Processed.

/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):

Chunk 60 Processed.

/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
/tmp/ipykernel_188/534607280.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):

Processing finished.

In [13]:
patients_df1 = patients_df[['osler_id','gender','birth_date']]
inpatient_df1 = inpatient_df[['osler_id','pat_enc_csn_id','adt_pat_class_c','adt_arrival_time','hosp_admsn_time','hosp_disch_time','admit_source_c','hosp_admsn_type_c',
                              'ed_visit_yn','emer_adm_date','dep_speciality','hospital_service','disch_disp_c']]
icustay_df1 = icustay_df[['osler_id','pat_enc_csn_id','in_time','out_time','seq','icu','origin']]
encounter_dx_df1 = encounter_dx_df[['osler_id','pat_enc_csn_id','dx_name','icd10_code','icd9_code','enc_contact_date','primary_dx_yn','dx_ed_yn','dx_qualifier','annotation']]

### Cardiac Arrest

In [14]:
encounter_dx_df1['name_search'] = encounter_dx_df1['dx_name'].transform(nameSearchCardiacArrest)
encounter_dx_df1['icd9_icd10'] = encounter_dx_df1['icd9_code'] + ' ' + encounter_dx_df1['icd10_code']
encounter_dx_df1['icd_search'] = encounter_dx_df1['icd9_icd10'].transform(icdSearchCardiacArrest)
ca_df = encounter_dx_df1[(encounter_dx_df1['name_search'])|(encounter_dx_df1['icd_search'])]

/tmp/ipykernel_188/2283379023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  encounter_dx_df1['name_search'] = encounter_dx_df1['dx_name'].transform(nameSearchCardiacArrest)
/tmp/ipykernel_188/2283379023.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  encounter_dx_df1['icd9_icd10'] = encounter_dx_df1['icd9_code'] + ' ' + encounter_dx_df1['icd10_code']
/tmp/ipykernel_188/2283379023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  encounter_dx_df1['icd_search'] = encounter_dx_df1['icd9_icd10'].transform(icdSearchCardiacArrest)

In [15]:
ca_df_tmp = ca_df[['osler_id','pat_enc_csn_id','enc_contact_date','dx_name','primary_dx_yn','dx_ed_yn','dx_qualifier','annotation']]
ca_df_tmp['primary_dx_yn'] = ca_df_tmp.groupby(['pat_enc_csn_id'])['primary_dx_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')
ca_df_tmp['dx_ed_yn'] = ca_df_tmp.groupby(['pat_enc_csn_id'])['dx_ed_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')

/tmp/ipykernel_188/632480073.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df_tmp['primary_dx_yn'] = ca_df_tmp.groupby(['pat_enc_csn_id'])['primary_dx_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')
/tmp/ipykernel_188/632480073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df_tmp['dx_ed_yn'] = ca_df_tmp.groupby(['pat_enc_csn_id'])['dx_ed_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')

In [16]:
ca_df_tmp['pat_enc_csn_id'].nunique()

8899

### OHCA

In [17]:
ip_df = pd.merge(patients_df1, inpatient_df1, on='osler_id', how='inner')
ca_ip_df = pd.merge(ca_df_tmp, ip_df, on=['osler_id','pat_enc_csn_id'], how='inner')
ca_ip_df['birth_date'] = pd.to_datetime(ca_ip_df['birth_date'], errors='coerce')
ca_ip_df['hosp_admsn_time'] = pd.to_datetime(ca_ip_df['hosp_admsn_time'], errors='coerce')
ca_ip_df = ca_ip_df.dropna(subset=['hosp_admsn_time'])
ca_ip_df['age'] = (ca_ip_df['hosp_admsn_time']-ca_ip_df['birth_date']).apply(lambda x: math.floor(x.days/365.25))
ca_ip_df = ca_ip_df[ca_ip_df['age'] >= 18]
ca_ip_df.loc[ca_ip_df['age'] > 100, 'age'] = 89  # match eICU
ca_ip_icu_df = pd.merge(ca_ip_df, icustay_df1, on=['osler_id','pat_enc_csn_id'], how='left')
ca_ip_icu_df = ca_ip_icu_df[ca_ip_icu_df['annotation']!='H/o cardiac arrest']

In [21]:
df = ca_ip_icu_df[(ca_ip_icu_df['seq']==1.0)|(ca_ip_icu_df['seq'].isna())]
df1 = df[df['hosp_admsn_type_c']!=3.0] # admission reason is non elective
df2 = df1[(df1['ed_visit_yn']=='Y')|(df1['origin']=='init')] # went through ED or was admitted straight to ICU
df3 = df2[(df2['dx_ed_yn']=='Y')|(df2['origin']=='init')] # diagnosis observed in ED or admitted straight to ICU

# merge dx_name
dx_name_df = df3.groupby('pat_enc_csn_id').agg({'dx_name': lambda x: '; '.join(x.unique())})
df3 = df3.drop(columns=['dx_name'])
df3 = pd.merge(df3, dx_name_df, on='pat_enc_csn_id', how='left')
df3 = df3.drop_duplicates(subset=['osler_id','pat_enc_csn_id'])

# drop patients with multiple encounters
grouped = df3.groupby('osler_id')['pat_enc_csn_id'].nunique()
duplicate_osler_ids = grouped[grouped > 1].index
df4 = df3[~df3['osler_id'].isin(duplicate_osler_ids)]

In [23]:
print('Cardiac arrest diagnoses:', ca_df_tmp['pat_enc_csn_id'].nunique())
print('Number of cardiac arrest encounters:', df['pat_enc_csn_id'].nunique())
print('Hospital admission is non elective:', df1['pat_enc_csn_id'].nunique())
print('Through ED or straight to ICU:', df2['pat_enc_csn_id'].nunique())
print('Diagnosis observed in ED or straight to ICU:', df3['pat_enc_csn_id'].nunique())
print(' duplicate osler_ids:', len(duplicate_osler_ids))
print('After removal of duplicates:', df4['pat_enc_csn_id'].nunique())

Cardiac arrest diagnoses: 8899
Number of cardiac arrest encounters: 4373
Hospital admission is non elective: 4036
Through ED or straight to ICU: 3751
Diagnosis observed in ED or straight to ICU: 2761
 duplicate osler_ids: 55
After removal of duplicates: 2649

In [24]:
ohca_df = df4.copy()
unique_osler_ids = pd.DataFrame(ohca_df['osler_id'])
unique_osler_ids.to_csv('ohca_osler_ids.csv',index=False)
unique_pat_enc_ids = pd.DataFrame(ohca_df['pat_enc_csn_id'])
unique_pat_enc_ids.to_csv('ohca_pat_enc_ids.csv',index=False)
ohca_df[['osler_id', 'pat_enc_csn_id', 'gender', 'birth_date', 'dx_name', 'hosp_admsn_time', 'hosp_disch_time', 'admit_source_c', 'disch_disp_c', 'ed_visit_yn']].to_csv('ohca.csv',index=False)

In [25]:
# icu_ohca_df = df4[df4['pat_enc_csn_id'].isin(icustay_df1['pat_enc_csn_id'])]
# unique_osler_ids = pd.DataFrame(icu_ohca_df['osler_id'])
# unique_osler_ids.to_csv('icu_ohca_osler_ids.csv',index=False)
# unique_pat_enc_ids = pd.DataFrame(icu_ohca_df['pat_enc_csn_id'])
# unique_pat_enc_ids.to_csv('icu_ohca_pat_enc_ids.csv',index=False)
# icu_ohca_df[['osler_id', 'pat_enc_csn_id', 'gender', 'birth_date', 'dx_name', 'hosp_admsn_time', 'hosp_disch_time', 'admit_source_c', 'disch_disp_c', 'ed_visit_yn']].to_csv('icu_ohca.csv',index=False)

In [26]:
ohca_df['pat_enc_csn_id'].nunique()

2649

In [27]:
ohca_df['osler_id'].nunique()

2649

In [28]:
ohca_df.shape

(2649, 27)

## old

#### out of hospital

In [72]:
df1 = df[df['admit_source_c']==1.0] # admission source is home/workplace/non-healthcare facility
df2 = df1[df1['hosp_admsn_type_c']!=3.0] # admission reason is non elective
df3 = df2[(df2['ed_visit_yn']=='Y')|(df2['origin']=='init')] # went through ED or was admitted straight to ICU

In [73]:
print('1. Admission source is non-healthcare:', df1['pat_enc_csn_id'].nunique())
print('2. Admission is non elective:', df2['pat_enc_csn_id'].nunique())
print('3. Patient went to ED or directly to ICU:', df3['pat_enc_csn_id'].nunique())

1. Admission source is non-healthcare: 3013
2. Admission is non elective: 2827
3. Patient went to ED or directly to ICU: 2784

#### primary_dx_yn

In [74]:
df4 = df3[df3['primary_dx_yn']=='Y']

In [75]:
print('Cardiac arrest is primary diagnosis:', df4['pat_enc_csn_id'].nunique())

Cardiac arrest is primary diagnosis: 1589

#### dx_qualifier x

In [48]:
print('Values:', df3['dx_qualifier'].unique())
print('Number of patients for which not NaN:', df3[~df3['dx_qualifier'].isna()]['pat_enc_csn_id'].nunique())

Values: [nan 'Active']
Number of patients for which not NaN: 1

#### annotation x

In [58]:
print('Number of patients for which not NaN:', df3[~df3['annotation'].isna()]['pat_enc_csn_id'].nunique())

Number of patients for which not NaN: 59

In [76]:
df3['annotation'].unique()

array([nan,
       'Cardiac arrest with pulseless electrical activity [I46.9 (ICD-10-CM)]',
       'PEA (Pulseless electrical activity) [I46.9 (ICD-10-CM)]',
       'Asystole [I46.9 (ICD-10-CM)]',
       'Cardiac arrest [I46.9 (ICD-10-CM)]',
       'Cardiopulmonary arrest [I46.9 (ICD-10-CM)]',
       'Traumatic cardiac arrest [I46.8 (ICD-10-CM)]',
       'Cardiac arrest [I46.9]',
       'Cardiac arrest with successful resuscitation [I46.9 (ICD-10-CM)]',
       'Traumatic cardiac arrest [I46.8]',
       'Cardiopulmonary arrest with successful resuscitation',
       'Cardiac arrest due to respiratory disorder [J98.9, I46.8 (ICD-10-CM)]',
       'Cardiopulmonary arrest with successful resuscitation [I46.9 (ICD-10-CM)]',
       'Cardiac arrest due to trauma [I46.8 (ICD-10-CM)]',
       'Cardiac arrest due to underlying cardiac condition [I46.2 (ICD-10-CM)]'],
      dtype=object)

#### dx_ed_yn

In [80]:
df3[df3['origin']=='init']['dx_ed_yn'].unique()

array(['N'], dtype=object)

In [82]:
print('Values:', df3['dx_ed_yn'].unique())
print(df3[df3['dx_ed_yn']=='Y']['pat_enc_csn_id'].nunique())
print(df3[(df3['dx_ed_yn']=='Y')|(df3['origin']=='init')]['pat_enc_csn_id'].nunique())

Values: ['Y' 'N']
2035
2039

In [88]:
df_tmp = df3[(df3['dx_ed_yn']=='Y')|(df3['origin']=='init')]

#### dep_speciality x

In [87]:
print(df3['dep_speciality'].unique())

['Emergency Medicine' nan 'Intensive Care' 'Medicine Surgery'
 'Orthopedic Surgery' 'Surgery' 'Oncology' 'Interventional Radiology'
 'Cardiology' 'Pediatric Intensive Care']

In [97]:
speciality = ['Emergency Medicine','Intensive Care','Cardiology','Pediatric Intensive Care']
df5 = df3[df3['dep_speciality'].isin(speciality)]
print(df5['pat_enc_csn_id'].nunique())

1504

In [94]:
df3[df3['dep_speciality'].isna()]['pat_enc_csn_id'].nunique()

785

In [99]:
df5['hospital_service'].unique()

array(['Emergency Medicine', 'Cardiology', 'Intensive Care',
       'Adult Emergency Medicine', 'Surgery', 'Medical ICU',
       'Internal Medicine', 'Intermediate Care', 'General Medicine',
       'Collaborative Internal Med', 'Trauma', 'Cardiac Cath',
       'ED Observation', 'Anesthesiology', 'Cardiac ICU', 'Medicine',
       'Cardiothoracic Surgery', 'Telemetry', 'Orthopedics',
       'Gastroenterology', 'Pulmonology', 'Critical Care'], dtype=object)

In [98]:
df3[df3['dep_speciality'].isna()]['hospital_service'].unique()

array(['Cardiology', 'Pulmonology', 'Cardiac Sur, Adult', 'ACS Janeway',
       'Clinical Skills Brancati', 'Collaborative Internal Med', 'Trauma',
       'Internal Medicine', 'Hospitalist Service', 'Surgery', 'Medicine',
       'Surgery Acute Care', 'Infectious Disease', 'ACS Barker',
       'Emergency Medicine', 'Gastroenterology', 'Medical Oncology',
       'Adult Neurology', 'Medicine - Housestaff', 'Neurology',
       'ACS Thayer', 'Plastics', 'Neurosurgery',
       'Neurosurgery - Brain Tumor', 'Neurology - Stroke',
       'Palliative Care Service', 'BMT IPOP PROGRAM', 'CIMS-IMC',
       'Orthopedics', 'Neurosurgery - Vascular', 'Burn', 'Obstetrics',
       'ACS Longcope', 'Renal', 'Pediatrics', 'Urology',
       'Intensive Treatment', 'Transplant, Adult', 'Adult Medicine',
       'Vascular Surgery', 'Adult Emergency Medicine',
       'Adult Ortho Spine', 'Gynecologic Oncology', 'Adult Orthopedics',
       'ED Observation', 'Otolaryngology/ENT'], dtype=object)

#### hospital_service

In [91]:
print(df3['hospital_service'].unique())

['Emergency Medicine' 'Cardiology' 'Internal Medicine' 'Pulmonology'
 'Intensive Care' 'Adult Emergency Medicine' 'Cardiac Sur, Adult'
 'ACS Janeway' 'Clinical Skills Brancati' 'Surgery'
 'Collaborative Internal Med' 'Trauma' 'Hospitalist Service' 'Medical ICU'
 'Intermediate Care' 'Medicine' 'Surgery Acute Care' 'Infectious Disease'
 'Cardiothoracic Surgery' 'ACS Barker' 'General Medicine'
 'Gastroenterology' 'Neurosurgery - Vascular' 'Medical Oncology'
 'Adult Neurology' 'Medicine - Housestaff' 'Neurology' 'ACS Thayer'
 'Plastics' 'Neurosurgery' 'Neurosurgery - Brain Tumor'
 'Neurology - Stroke' 'Palliative Care Service' 'BMT IPOP PROGRAM'
 'CIMS-IMC' 'Cardiac Cath' 'Orthopedics' 'Burn' 'Cardiac ICU' 'Obstetrics'
 'ACS Longcope' 'Renal' 'ED Observation' 'Pediatrics' 'Anesthesiology'
 'Urology' 'Intensive Treatment' 'Transplant, Adult' 'Adult Medicine'
 'Vascular Surgery' 'Adult Ortho Spine' 'Gynecologic Oncology' 'Telemetry'
 'Adult Orthopedics' 'Critical Care' 'Oncology' 'Otolaryngology/ENT']

In [102]:
services = ['Emergency Medicine',
            'Cardiology',
            'Intensive Care',
            'Adult Emergency Medicine',
            'Medical ICU',
            'Intermediate Care',
            'Adult Neurology',
            'Neurology',
            'Cardiac Cath',
            'Cardiac ICU',
            'ED Observation',
            'Intensive Treatment',
            'Telemetry',
            'Critical Care']
df6 = df3[df3['hospital_service'].isin(services)]
print(df6['pat_enc_csn_id'].nunique())

1793

### CA inpatient

In [11]:
ip_df = pd.merge(patients_df1, inpatient_df1, on='osler_id', how='inner')
ca_inpatient_df = pd.merge(ca_df, ip_df, on=['osler_id','pat_enc_csn_id'], how='inner')

In [12]:
print(ca_df['pat_enc_csn_id'].nunique())
print(ca_inpatient_df['pat_enc_csn_id'].nunique())

8899
4880

In [13]:
print(ca_df['osler_id'].nunique())
print(ca_inpatient_df['osler_id'].nunique())

5018
4487

In [19]:
mount_s_drive(subfolder='LCICM/Isalis')

Password for ikarhul1: ········

Mounting S drive subfolder LCICM/Isalis

mkdir: cannot create directory '/home/idies/workspace/SAFE/': File exists

The following files and folders have been mounted to /home/idies/workspace/SAFE/:
  PMAP_ICU_CA_osler_ids.txt
  Isalis_vitals_data.csv
  d_flo_measures.csv
  Isalis_Flowsheet_part1.csv
  Isalis_Flowsheet_part2.csv
  Flowsheet_ICU_CA.csv
  Isalis_fever_dur.csv
  core.info_adm_death.csv
  merged.csv

In [24]:
def read_flowsheet(file_path,chunk_size=1e6,head='infer'):
    df_chunks = []
    num_chunks = 0    
    for chunk in pd.read_csv(file_path,chunksize=chunk_size,header=head):
        chunk.columns = ['osler_id','pat_enc_csn_id','inpatient_data_id','recorded_time','meas_value',
                         'meas_comment','meas_id','meas_row_type_c','meas_val_type_c','meas_template_id',
                         'meas_fsd_id','meas_line','meas_occurance','rw_meas_id',
                         'ip_lda_id','rw_row_type_c','rw_val_type_c','meas_taken_user_id']
        df_chunks.append(chunk)
        if num_chunks % 20 == 0:
            print(f'Chunk {num_chunks} Processed.')
        num_chunks += 1
        del chunk
    print('Processing finished.')    
    return pd.concat(df_chunks, ignore_index=True)

In [25]:
flowsheet_df1 = read_flowsheet(data_dir+'Isalis_Flowsheet_part1.csv',head=None)
flowsheet_df2 = read_flowsheet(data_dir+'Isalis_Flowsheet_part2.csv',head=None)
flowsheet_df = pd.concat([flowsheet_df1,flowsheet_df2],ignore_index=True)
del flowsheet_df1
del flowsheet_df2

Chunk 0 Processed.
Chunk 20 Processed.
Chunk 40 Processed.
Chunk 60 Processed.
Processing finished.
Chunk 0 Processed.
Chunk 20 Processed.
Chunk 40 Processed.
Chunk 60 Processed.
Processing finished.

In [26]:
flowsheet_df['osler_id'].nunique()

2853

In [28]:
ca_inpatient_df[~ca_inpatient_df['osler_id'].isin(flowsheet_df['osler_id'])]['osler_id'].nunique()

1634

In [29]:
1634 + 2853

4487

In [30]:
unique_osler_ids = ca_inpatient_df[~ca_inpatient_df['osler_id'].isin(flowsheet_df['osler_id'])]['osler_id'].drop_duplicates()
unique_osler_ids.to_excel('PMAP_osler_ids.xlsx', index=False, header=False)

In [31]:
len(unique_osler_ids)

1634

In [32]:
unique_osler_ids.to_excel('/home/idies/workspace/SAFE/PMAP_osler_ids.xlsx', index=False, header=False)

### OHCA

In [76]:
ip_df = pd.merge(patients_df1, inpatient_df1, on='osler_id', how='inner')
ca_inpatient_df = pd.merge(ca_df_tmp, ip_df, on=['osler_id','pat_enc_csn_id'], how='inner')
ca_inpatient_df['birth_date'] = pd.to_datetime(ca_inpatient_df['birth_date'], errors='coerce')
ca_inpatient_df['hosp_admsn_time'] = pd.to_datetime(ca_inpatient_df['hosp_admsn_time'], errors='coerce')
ca_inpatient_df = ca_inpatient_df.dropna(subset=['hosp_admsn_time'])
ca_inpatient_df['age'] = (ca_inpatient_df['hosp_admsn_time']-ca_inpatient_df['birth_date']).apply(lambda x: math.floor(x.days/365.25))
ca_inpatient_df_u18 = ca_inpatient_df[ca_inpatient_df['age'] < 18]
ca_inpatient_df = ca_inpatient_df[ca_inpatient_df['age'] >= 18]
ca_inpatient_df.loc[ca_inpatient_df['age'] > 89, 'age'] = 89  # to match eICU

In [77]:
ohca_df = ca_inpatient_df[ca_inpatient_df['admit_source_c']==1.0]
ohca_df = ohca_df[(ohca_df['hosp_admsn_type_c']!=3.0)&(~ohca_df['hosp_admsn_type_c'].isna())]

In [80]:
non2_ohca_df = ohca_df.copy()
dx_name_df = non2_ohca_df.groupby('pat_enc_csn_id').agg({'dx_name': lambda x: '; '.join(x.unique())})
non2_ohca_df = non2_ohca_df.drop(columns=['dx_name'])
non2_ohca_df = pd.merge(non2_ohca_df, dx_name_df, on='pat_enc_csn_id', how='left')
non2_ohca_df = non2_ohca_df.drop_duplicates(subset=['osler_id','pat_enc_csn_id'])
grouped = non2_ohca_df.groupby('osler_id')['pat_enc_csn_id'].nunique()
duplicate_osler_ids = grouped[grouped > 1].index
non2_ohca_df = non2_ohca_df[~non2_ohca_df['osler_id'].isin(duplicate_osler_ids)]
len(duplicate_osler_ids)

18

In [83]:
print('Encounters:')
print(' Cardiac arrest:', ca_df['pat_enc_csn_id'].nunique())
print(' Cardiac arrest is primary diagnosis:', ca_df_tmp['pat_enc_csn_id'].nunique())
print(' Cardiac arrest is primary diagnosis with inpatient:', ca_inpatient_df['pat_enc_csn_id'].nunique())
print(' Admit source is non-healthcare and admission is non-elective:', ohca_df['pat_enc_csn_id'].nunique())
print(' After exclusion of patients with multiple encounters:', non2_ohca_df['pat_enc_csn_id'].nunique())
print(' Have recorded ICU stay:', non2_ohca_df[non2_ohca_df['pat_enc_csn_id'].isin(icustay_df1['pat_enc_csn_id'])]['pat_enc_csn_id'].nunique())

Encounters:
 Cardiac arrest: 8899
 Cardiac arrest is primary diagnosis: 3433
 Cardiac arrest is primary diagnosis with inpatient: 2131
 Admit source is non-healthcare and admission is non-elective: 1728
 After exclusion of patients with multiple encounters: 1691
 Have recorded ICU stay: 923

In [84]:
print('Patients:')
print(' Cardiac arrest:', ca_df['osler_id'].nunique())
print(' Cardiac arrest is primary diagnosis:', ca_df_tmp['osler_id'].nunique())
print(' Cardiac arrest is primary diagnosis with inpatient:', ca_inpatient_df['osler_id'].nunique())
print(' Admit source is non-healthcare and admission is non-elective:', ohca_df['osler_id'].nunique())
print(' After exclusion of patients with multiple encounters:', non2_ohca_df['osler_id'].nunique())
print(' Have recorded ICU stay:', non2_ohca_df[non2_ohca_df['pat_enc_csn_id'].isin(icustay_df1['pat_enc_csn_id'])]['osler_id'].nunique())

Patients:
 Cardiac arrest: 5018
 Cardiac arrest is primary diagnosis: 2638
 Cardiac arrest is primary diagnosis with inpatient: 2090
 Admit source is non-healthcare and admission is non-elective: 1709
 After exclusion of patients with multiple encounters: 1691
 Have recorded ICU stay: 923

In [89]:
unique_osler_ids = pd.DataFrame(non2_ohca_df['osler_id'])
unique_osler_ids.to_csv('ohca_osler_ids.csv',index=False)
unique_pat_enc_ids = pd.DataFrame(non2_ohca_df['pat_enc_csn_id'])
unique_pat_enc_ids.to_csv('ohca_pat_enc_ids.csv',index=False)
non2_ohca_df.to_csv('ohca.csv',index=False)

In [90]:
icu_ohca_df = non2_ohca_df[non2_ohca_df['pat_enc_csn_id'].isin(icustay_df1['pat_enc_csn_id'])]
unique_osler_ids = pd.DataFrame(icu_ohca_df['osler_id'])
unique_osler_ids.to_csv('icu_ohca_osler_ids.csv',index=False)
unique_pat_enc_ids = pd.DataFrame(icu_ohca_df['pat_enc_csn_id'])
unique_pat_enc_ids.to_csv('icu_ohca_pat_enc_ids.csv',index=False)
icu_ohca_df.to_csv('icu_ohca.csv',index=False)

In [87]:
ip_df = pd.merge(patients_df1, inpatient_df1, on='osler_id', how='inner')
ca_inpatient_df = pd.merge(ca_df_tmp, ip_df, on=['osler_id','pat_enc_csn_id'], how='inner')
icu_ca_df = pd.merge(ca_inpatient_df, icustay_df1, on=['osler_id','pat_enc_csn_id'], how='inner')
icu_ca_df['in_time'] = pd.to_datetime(icu_ca_df['in_time'], errors='coerce')
icu_ca_df['out_time'] = pd.to_datetime(icu_ca_df['out_time'], errors='coerce')
print('Number of ICU CA patients:', icu_ca_df['pat_enc_csn_id'].nunique())
dx_name_df = icu_ca_df.groupby('pat_enc_csn_id').agg({'dx_name': lambda x: '; '.join(x.unique())})
icu_ca_df = icu_ca_df.drop(columns=['dx_name'])
icu_ca_df = pd.merge(icu_ca_df, dx_name_df, on='pat_enc_csn_id', how='left')
icu_ca_df['primary_dx_yn'] = icu_ca_df.groupby(['pat_enc_csn_id'])['primary_dx_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')
icu_ca_df['dx_ed_yn'] = icu_ca_df.groupby(['pat_enc_csn_id'])['dx_ed_yn'].transform(lambda x: 'Y' if 'Y' in x.values else 'N')
icu_seq1_df = icu_ca_df[icu_ca_df['seq']==1]
icu_seq2_df = icu_ca_df[icu_ca_df['seq']==2]
columns = list(set(icu_ca_df.columns) - {'origin','icu','in_time', 'out_time'})
icu_ca_df = pd.merge(icu_seq1_df, icu_seq2_df, on=columns, how='left')
icu_ca_df['in_time'] = icu_ca_df[['in_time_x', 'in_time_y']].min(axis=1)
icu_ca_df['out_time'] = icu_ca_df[['out_time_x', 'out_time_y']].max(axis=1)
icu_ca_df['icu'] = icu_ca_df['icu_x']
icu_ca_df['origin'] = icu_ca_df['origin_x']
icu_ca_df = icu_ca_df.drop(columns=['in_time_x', 'in_time_y','out_time_x', 'out_time_y',
                                    'icu_x', 'icu_y','origin_x','origin_y','seq']).reset_index(drop=True)
icu_ca_df = icu_ca_df.sort_values(['osler_id','hosp_admsn_time','in_time']).reset_index(drop=True)
icu_ca_df = icu_ca_df.drop_duplicates(subset=['osler_id','pat_enc_csn_id'])
grouped = icu_ca_df.groupby('osler_id')['pat_enc_csn_id'].nunique()
duplicate_osler_ids = grouped[grouped > 1].index
icu_ca_df = icu_ca_df[~icu_ca_df['osler_id'].isin(duplicate_osler_ids)]
print(' after exclusion of patients with multiple encounters:', icu_ca_df['pat_enc_csn_id'].nunique())
len(duplicate_osler_ids)

Number of ICU CA patients: 1335
 after exclusion of patients with multiple encounters: 1316

9

In [88]:
ohca_df2 = icu_ca_df.copy()
ohca_df2 = icu_ca_df[icu_ca_df['admit_source_c']==1.0]
ohca_df2 = ohca_df2[(ohca_df2['hosp_admsn_type_c']!=3.0)&(~ohca_df['hosp_admsn_type_c'].isna())]
ohca_df2.shape

/tmp/ipykernel_136/153229117.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ohca_df2 = ohca_df2[(ohca_df2['hosp_admsn_type_c']!=3.0)&(~ohca_df['hosp_admsn_type_c'].isna())]

(712, 21)

In [425]:
unique_osler_ids = pd.DataFrame(ohca_df2['osler_id'])
unique_osler_ids.to_csv('ohca_osler_ids.csv',index=False)
unique_pat_enc_ids = pd.DataFrame(ohca_df2['pat_enc_csn_id'])
unique_pat_enc_ids.to_csv('ohca_pat_enc_ids.csv',index=False)
ohca_df2.to_csv('ohca.csv',index=False)

#### (old) Hospital Service / ICU Service / ICU Admission Offset

In [10]:
icu_patients_df = pd.merge(patients_df1,icustay_df1,on='osler_id',how='inner')
icu_inpatient_df = pd.merge(icu_patients_df,inpatient_df1,on=['osler_id','pat_enc_csn_id'],how='left')
icu_inpatient_df['birth_date'] = pd.to_datetime(icu_inpatient_df['birth_date'], errors='coerce')
icu_inpatient_df['hosp_admsn_time'] = pd.to_datetime(icu_inpatient_df['hosp_admsn_time'], errors='coerce')
icu_inpatient_df['hosp_disch_time'] = pd.to_datetime(icu_inpatient_df['hosp_disch_time'], errors='coerce')
icu_inpatient_df['in_time'] = pd.to_datetime(icu_inpatient_df['in_time'], errors = 'coerce')
icu_inpatient_df['out_time'] = pd.to_datetime(icu_inpatient_df['out_time'], errors = 'coerce')
icu_inpatient_df['icu_admsn_offset'] = (icu_inpatient_df['in_time']-icu_inpatient_df['hosp_admsn_time']).dt.total_seconds()/60
icu_inpatient_df['age'] = (icu_inpatient_df['hosp_admsn_time']-icu_inpatient_df['birth_date']).apply(lambda x: math.floor(x.days/365.25))
icu_inpatient_df = icu_inpatient_df[icu_inpatient_df['age'] >= 18]
icu_inpatient_df.loc[icu_inpatient_df['age'] > 89, 'age'] = 89
icu_ca_df = pd.merge(icu_inpatient_df, ca_df, on=['osler_id','pat_enc_csn_id'], how='inner')
print('Number of ICU CA patients:', icu_ca_df['pat_enc_csn_id'].nunique())
dx_name_df = icu_ca_df.groupby('pat_enc_csn_id').agg({'dx_name': lambda x: '; '.join(x.unique())})
icu_ca_df = icu_ca_df.drop(columns=['dx_name'])
icu_ca_df = pd.merge(icu_ca_df, dx_name_df, on='pat_enc_csn_id', how='left')
icu_seq1_df = icu_ca_df[icu_ca_df['seq']==1]
icu_seq2_df = icu_ca_df[icu_ca_df['seq']==2]
columns = ['osler_id', 'gender', 'birth_date', 'pat_enc_csn_id', 'seq', 'icu', 'hosp_admsn_time', 'hosp_disch_time', 'hospital_service','icu_admsn_offset',
           'disch_disp_c', 'age', 'dx_name', 'icd10_code', 'icd9_code', 'enc_contact_date', 'name_search','icd9_icd10', 'icd_search']
icu_ca_df = pd.merge(icu_seq1_df, icu_seq2_df, on=columns, how='left')
icu_ca_df['in_time'] = icu_ca_df[['in_time_x', 'in_time_y']].min(axis=1)
icu_ca_df['out_time'] = icu_ca_df[['out_time_x', 'out_time_y']].max(axis=1)
icu_ca_df = icu_ca_df.drop(columns=['in_time_x', 'in_time_y', 'out_time_x', 'out_time_y']).reset_index(drop=True)
icu_ca_df = icu_ca_df.sort_values(['osler_id','hosp_admsn_time','in_time']).reset_index(drop=True)
icu_ca_df = icu_ca_df.drop_duplicates(subset=['osler_id','pat_enc_csn_id','hosp_admsn_time','in_time','dx_name'])
grouped = icu_ca_df.groupby('osler_id')['pat_enc_csn_id'].nunique()
duplicate_osler_ids = grouped[grouped > 1].index
icu_ca_df = icu_ca_df[~icu_ca_df['osler_id'].isin(duplicate_osler_ids)]
print(' after exclusion of patients with multiple encounters:', icu_ca_df['pat_enc_csn_id'].nunique())

Number of ICU CA patients: 2928
 after exclusion of patients with multiple encounters: 2807

In [11]:
print(len(duplicate_osler_ids))

60

In [25]:
icu_ca_df['hospital_service'].unique()

array(['Hospitalist Service', 'Cardiology', 'Trauma', 'Cardiac ICU',
       'Clinical Skills Brancati', 'Internal Medicine', 'Adult Neurology',
       'Intensive Care', 'Medicine', 'Burn', 'Pulmonology',
       'General Medicine', 'Medical Oncology', 'Pediatrics',
       'ACS Longcope', 'BMT IPOP PROGRAM', 'Surgery',
       'Cardiac Sur, Adult', 'Surgery Acute Care',
       'Neurosurgery - Vascular', 'Adult Ortho Spine', 'ACS Thayer',
       'Neurology', 'Collaborative Internal Med', 'Transplant, Adult',
       'Medical ICU', 'ACS Janeway', 'Neurology - Stroke', 'Orthopedics',
       'Cardiothoracic Surgery', 'Colorectal Surgery',
       'Emergency Medicine', 'Urology', 'ACS Barker',
       'Neurosurgery - Brain Tumor', 'Gynecologic Oncology',
       'Neurosurgery - Spine', 'Neurosurgery', 'Obstetrics', 'Renal',
       'Telemetry', 'Intermediate Care', 'CIMS-IMC', 'Plastics',
       'Adult Orthopedics', 'Anesthesiology', 'Thoracic Surgery',
       'Adult Emergency Medicine', 'Sur Onc/Endoc, Adult',
       'GI Surgery, Adult', 'Vascular Surgery', 'ED Observation',
       'Medicine - Housestaff', 'Otolaryngology/ENT',
       'Infectious Disease', 'Adult Otolaryngology', 'Cardiac Cath',
       'Hepatopancreatobiliary Surgery', 'Plastics, Adult',
       'Physical Medicine and Rehabilitation', 'Critical Care',
       'Adult Medicine', 'Hydrocephalus', 'Palliative Care Service',
       'Neuro Research', 'Gynecology', 'Intensive Treatment',
       'Hematology', 'Gastroenterology'], dtype=object)

In [49]:
icu_ca_df['icu'].unique()

array(['micu', 'bmc_cicu', 'bmc_sicu', 'hoco_icu', 'nccu', 'sh_icu',
       'bmc_micu', 'bmc_burn_icu', 'cvsicu', 'onc_micu', 'picu',
       'smh_icu', 'ccu', 'wicu', 'sicu', 'bmc_nccu', 'ach_picu',
       'ach_cvicu'], dtype=object)

In [101]:
ohca_df = icu_ca_df[['osler_id','pat_enc_csn_id','hosp_admsn_time','hosp_disch_time','in_time','out_time','icu_admsn_offset','icu','hospital_service','dx_name','disch_disp_c']]
icus = ['micu','bmc_cicu','hoco_icu','sh_icu','bmc_micu','cvsicu','smh_icu','ccu','bmc_nccu']
hospital_services = ['Hospitalist Service','Cardiology','Trauma','Cardiac ICU','Clinical Skills Brancati','Internal Medicine',
                     'Intensive Care','Medicine','General Medicine','ACS Longcope','Medical ICU','Emergency Medicine',
                     'Intermediate Care','Adult Emergency Medicine','ED Observation','Cardiac Cath','Critical Care','Adult Medicine',
                     'Collaborative Internal Med','Telemetry','CIMS-IMC','Intensive Treatment']
ohca_df = ohca_df[ohca_df['icu'].isin(icus)]
ohca_df = ohca_df[ohca_df['hospital_service'].isin(hospital_services)]
ohca_df = ohca_df[ohca_df['icu_admsn_offset']<=240]
ohca_df.reset_index(drop=True,inplace=True)

In [102]:
ohca_df.shape

(1019, 11)

In [103]:
ohca_df

,osler_id,pat_enc_csn_id,hosp_admsn_time,hosp_disch_time,in_time,out_time,icu_admsn_offset,icu,hospital_service,dx_name,disch_disp_c
0,00345014-60f2-4b08-b542-d174e11df17a,1257426946,2017-10-04 00:15:00,2017-10-10 05:48:00,2017-10-04 02:56:00,2017-10-05 21:30:00,161.0,micu,Hospitalist Service,Cardiopulmonary arrest,20.0
1,00ac2c52-a69b-49da-933b-b24ed3915197,1300955947,2019-12-12 13:03:00,2019-12-12 19:30:00,2019-12-12 16:26:00,2019-12-12 19:30:00,203.0,hoco_icu,Cardiac ICU,Cardiac arrest due to underlying cardiac condi...,2.0
2,00afe63a-a15c-4666-a75d-efde23fc891d,1408906075,2023-08-04 12:52:00,2023-08-19 13:45:00,2023-08-04 12:52:00,2023-08-06 18:22:00,0.0,micu,Clinical Skills Brancati,Cardiac arrest,1.0
3,013ca9aa-86b2-4ecd-bcbb-64a4ac4ed01d,1255219881,2017-08-21 13:41:00,2017-09-09 04:13:00,2017-08-21 16:12:00,2017-09-09 04:13:00,151.0,sh_icu,Intensive Care,Cardiac arrest,20.0
4,016e7e4c-7cb7-4e9b-b531-7f1d8b72cb3b,1322274910,2020-11-07 06:52:00,2020-11-08 09:45:00,2020-11-07 08:40:00,2020-11-08 09:45:00,108.0,sh_icu,Intensive Care,Cardiac arrest; Cardiopulmonary arrest,20.0
...,...,...,...,...,...,...,...,...,...,...,...
1014,ff336266-1650-4def-b327-952e97f2b5f5,1171791241,2016-07-10 22:00:00,2016-07-14 20:41:00,2016-07-10 22:00:00,2016-07-14 20:41:00,0.0,ccu,Cardiology,Cardiac arrest,20.0
1015,ff5e2f68-7b30-4893-8b51-a577e1b38912,1365474393,2022-03-18 12:54:00,2022-04-12 23:12:00,2022-03-18 15:53:00,2022-03-25 21:31:00,179.0,hoco_icu,Internal Medicine,Cardiac arrest,20.0
1016,ff801134-6c7b-48b8-942a-4e1c59e8477e,1395635742,2023-03-04 10:57:00,2023-03-10 09:25:00,2023-03-04 14:07:00,2023-03-10 08:03:00,190.0,bmc_cicu,Cardiology,PEA (Pulseless electrical activity); Cardiac a...,20.0
1017,ffa46184-fc9d-4518-8bb0-1bd1ff9668e4,1269314674,2018-05-15 11:56:00,2018-05-18 04:00:00,2018-05-15 14:29:00,2018-05-18 04:00:00,153.0,hoco_icu,Intensive Care,Cardiac arrest,20.0
1018,ffb6561f-153d-4263-af4d-6b1fd3964b14,1169400527,2016-06-18 06:35:00,2016-06-18 13:18:00,2016-06-18 08:53:00,2016-06-18 11:00:00,138.0,bmc_cicu,Cardiology,Cardiac arrest,20.0

In [109]:
unique_osler_ids = pd.DataFrame(ohca_df['osler_id'])
unique_osler_ids.to_csv('ohca_osler_ids.csv',index=False)
unique_osler_ids

                                  osler_id
0     00345014-60f2-4b08-b542-d174e11df17a
1     00ac2c52-a69b-49da-933b-b24ed3915197
2     00afe63a-a15c-4666-a75d-efde23fc891d
3     013ca9aa-86b2-4ecd-bcbb-64a4ac4ed01d
4     016e7e4c-7cb7-4e9b-b531-7f1d8b72cb3b
...                                    ...
1014  ff336266-1650-4def-b327-952e97f2b5f5
1015  ff5e2f68-7b30-4893-8b51-a577e1b38912
1016  ff801134-6c7b-48b8-942a-4e1c59e8477e
1017  ffa46184-fc9d-4518-8bb0-1bd1ff9668e4
1018  ffb6561f-153d-4263-af4d-6b1fd3964b14

[1019 rows x 1 columns]

In [110]:
unique_pat_enc_ids = pd.DataFrame(ohca_df['pat_enc_csn_id'])
unique_pat_enc_ids.to_csv('ohca_pat_enc_ids.csv',index=False)
unique_pat_enc_ids

      pat_enc_csn_id
0         1257426946
1         1300955947
2         1408906075
3         1255219881
4         1322274910
...              ...
1014      1171791241
1015      1365474393
1016      1395635742
1017      1269314674
1018      1169400527

[1019 rows x 1 columns]

In [113]:
ohca_df.to_csv('ohca.csv',index=False)
ohca_df

,osler_id,pat_enc_csn_id,hosp_admsn_time,hosp_disch_time,in_time,out_time,icu_admsn_offset,icu,hospital_service,dx_name,disch_disp_c
0,00345014-60f2-4b08-b542-d174e11df17a,1257426946,2017-10-04 00:15:00,2017-10-10 05:48:00,2017-10-04 02:56:00,2017-10-05 21:30:00,161.0,micu,Hospitalist Service,Cardiopulmonary arrest,20.0
1,00ac2c52-a69b-49da-933b-b24ed3915197,1300955947,2019-12-12 13:03:00,2019-12-12 19:30:00,2019-12-12 16:26:00,2019-12-12 19:30:00,203.0,hoco_icu,Cardiac ICU,Cardiac arrest due to underlying cardiac condi...,2.0
2,00afe63a-a15c-4666-a75d-efde23fc891d,1408906075,2023-08-04 12:52:00,2023-08-19 13:45:00,2023-08-04 12:52:00,2023-08-06 18:22:00,0.0,micu,Clinical Skills Brancati,Cardiac arrest,1.0
3,013ca9aa-86b2-4ecd-bcbb-64a4ac4ed01d,1255219881,2017-08-21 13:41:00,2017-09-09 04:13:00,2017-08-21 16:12:00,2017-09-09 04:13:00,151.0,sh_icu,Intensive Care,Cardiac arrest,20.0
4,016e7e4c-7cb7-4e9b-b531-7f1d8b72cb3b,1322274910,2020-11-07 06:52:00,2020-11-08 09:45:00,2020-11-07 08:40:00,2020-11-08 09:45:00,108.0,sh_icu,Intensive Care,Cardiac arrest; Cardiopulmonary arrest,20.0
...,...,...,...,...,...,...,...,...,...,...,...
1014,ff336266-1650-4def-b327-952e97f2b5f5,1171791241,2016-07-10 22:00:00,2016-07-14 20:41:00,2016-07-10 22:00:00,2016-07-14 20:41:00,0.0,ccu,Cardiology,Cardiac arrest,20.0
1015,ff5e2f68-7b30-4893-8b51-a577e1b38912,1365474393,2022-03-18 12:54:00,2022-04-12 23:12:00,2022-03-18 15:53:00,2022-03-25 21:31:00,179.0,hoco_icu,Internal Medicine,Cardiac arrest,20.0
1016,ff801134-6c7b-48b8-942a-4e1c59e8477e,1395635742,2023-03-04 10:57:00,2023-03-10 09:25:00,2023-03-04 14:07:00,2023-03-10 08:03:00,190.0,bmc_cicu,Cardiology,PEA (Pulseless electrical activity); Cardiac a...,20.0
1017,ffa46184-fc9d-4518-8bb0-1bd1ff9668e4,1269314674,2018-05-15 11:56:00,2018-05-18 04:00:00,2018-05-15 14:29:00,2018-05-18 04:00:00,153.0,hoco_icu,Intensive Care,Cardiac arrest,20.0
1018,ffb6561f-153d-4263-af4d-6b1fd3964b14,1169400527,2016-06-18 06:35:00,2016-06-18 13:18:00,2016-06-18 08:53:00,2016-06-18 11:00:00,138.0,bmc_cicu,Cardiology,Cardiac arrest,20.0