In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import math

import sys
# sys.path.append('..')
# from mount_drive import mount_s_drive

In [2]:
# mount_s_drive(subfolder='LCICM')

In [3]:
data_dir = '/projects/'

In [4]:
file_path = data_dir+'/ACCMPMAP/dbo.accm_flowsheet.csv'
myHeader = pd.read_csv(file_path, nrows=1)

FileNotFoundError: [Errno 2] No such file or directory: '/projects//ACCMPMAP/dbo.accm_flowsheet.csv'

In [6]:
myHeader

,osler_id,pat_enc_csn_id,inpatient_data_id,recorded_time,meas_value,meas_comment,meas_id,meas_row_type_c,meas_val_type_c,meas_template_id,meas_fsd_id,meas_line,meas_occurance,rw_meas_id,ip_lda_id,rw_row_type_c,rw_val_type_c,meas_taken_user_id,RN
0,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.155891e+09,18599880.0,2016-03-08 15:59:00,Hand Therapy,NaN,3044010007169,1,8,3044010007167,11348532,44,NaN,NaN,NaN,NaN,NaN,HCOOK1,2

In [7]:
myDflo = pd.read_csv(data_dir + '/d_flo_measures.csv')

In [8]:
myDflow = pd.read_csv(data_dir + '/Flowsheet_ICU_CA.csv')

In [9]:
myIds = pd.read_csv('../Isalis/PMAP_ICU_CA_osler_ids.txt', header=None)

In [10]:
myIds[0]

0       0196a254-198c-4ba7-877c-44a6181f0db8
1       0ef927eb-6bcd-45f6-8e42-b09be976ac84
2       2dbc61ea-8cd1-42ea-8085-fa107209fd11
3       52492eb5-095c-41c7-9986-96e371ef8f3a
4       637b4e38-6d6b-4b32-ae6f-1ffea73b6cd0
                        ...
2853    bc93b277-895a-4a71-916f-3eb7676cfdec
2854    c09cbe00-b3b9-4eb7-bd70-8701b5166982
2855    c8326373-f34f-4314-9cb2-8ed13df147fb
2856    eca74923-9449-40a4-9ff0-3fe036114f55
2857    fc50b1bd-fdb0-4069-93c5-208fb47245e8
Name: 0, Length: 2858, dtype: object

In [16]:
# file_path = data_dir+'/Databases/ACCMPMAP'
# # myLabs = pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv')
# chunk_size = 1e6
# chunks = []
# i = 0
# for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size, low_memory=False):
#     chunk = chunk[chunk['osler_id'].isin(myIds[0])]
#     chunks.append(chunk)
#     print(f'chunk {i}')
#     i+=1
#     del chunk

# myLabsDf = pd.concat(chunks, ignore_index=True)

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 0

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 1

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 2

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 3

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 4

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 5

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 6

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 7

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 8

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 9

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 10

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 11

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 12

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 13

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 14

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 15

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 16

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 17

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 18

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 19

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 20

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 21

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 22

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 23

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 24

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 25

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 26

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 27

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 28

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 29

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 30

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 31

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 32

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 33

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 34

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 35

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 36

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 37

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 38

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 39

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 40

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 41

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 42

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 43

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 44

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 45

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 46

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 47

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 48

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 49

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 50

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 51

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 52

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 53

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 54

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 55

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 56

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 57

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 58

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 59

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 60

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 61

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 62

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 63

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 64

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 65

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 66

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 67

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 68

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 69

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 70

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 71

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 72

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 73

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 74

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 75

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 76

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 77

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 78

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 79

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 80

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 81

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 82

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 83

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 84

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 85

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 86

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 87

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 88

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 89

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 90

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 91

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 92

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 93

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 94

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 95

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 96

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 97

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 98

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 99

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 100

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 101

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 102

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 103

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 104

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 105

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 106

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 107

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 108

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 109

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 110

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 111

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 112

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 113

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 114

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 115

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 116

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 117

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 118

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 119

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 120

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 121

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 122

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 123

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 124

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 125

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 126

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 127

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 128

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 129

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 130

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 131

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 132

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 133

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 134

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 135

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 136

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 137

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 138

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 139

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 140

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 141

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 142

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 143

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 144

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 145

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 146

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 147

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 148

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 149

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 150

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 151

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 152

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 153

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 154
chunk 155

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 156

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 157

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 158

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 159

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 160

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 161

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 162

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 163

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 164

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 165

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 166

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 167

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 168

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 169

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 170

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 171

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 172

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 173

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 174

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 175

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 176

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 177

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 178

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 179

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 180

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 181

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 182

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 183

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 184

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 185

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 186

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (16,25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 187

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 188

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 189

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 190

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 191

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 192

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 193

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 194

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 195

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 196

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 197

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 198

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 199

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 200

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 201

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 202

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 203

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 204

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 205

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 206

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 207

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 208

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 209

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 210

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 211

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 212

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 213

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 214

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 215

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 216

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 217

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 218

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 219

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 220

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 221

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 222

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 223

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 224

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 225

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 226

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (16,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 227

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 228

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 229

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 230

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 231

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 232

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 233

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 234

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 235

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 236

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 237

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 238

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 239

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 240

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 241

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 242

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 243

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 244

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 245

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 246

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 247

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 248

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 249

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 250

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 251

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 252

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 253

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 254

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 255

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 256

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 257

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 258

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 259

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 260

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 261

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 262

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 263

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 264

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 265

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 266

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 267

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 268

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 269

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 270

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 271

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 272

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 273

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 274

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 275

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 276

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 277

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 278

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 279

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 280

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 281

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 282

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 283

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 284

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 285

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 286

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 287

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 288

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 289

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 290

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 291

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 292

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 293

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 294

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 295

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 296

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 297

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 298

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 299

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 300

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 301

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 302

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 303

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 304

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 305

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 306

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 307

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 308

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 309

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 310

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 311

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 312

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 313

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 314

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 315

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 316

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 317

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 318

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 319

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 320

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 321

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 322

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 323

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 324

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 325

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 326

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 327

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 328

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 329

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 330

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 331

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 332

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 333

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 334

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 335

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 336

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 337

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 338

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 339

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 340

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 341

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 342

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 343

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 344

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 345

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 346

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 347

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 348

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 349

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 350

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 351

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 352

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 353

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 354

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 355

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 356

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 357

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 358

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 359

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 360

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 361

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 362

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 363

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 364

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 365

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 366

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 367

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 368

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 369

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 370

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 371

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 372

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 373

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 374

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 375

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 376

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 377

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 378

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 379

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 380

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 381

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 382

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 383

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 384

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 385

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 386

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 387

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 388

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 389

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 390

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 391

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 392

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 393

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 394

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 395

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 396

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 397

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 398

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 399

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 400

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 401

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 402

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 403

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 404

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 405

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 406

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 407

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 408

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 409

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 410

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 411

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 412

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 413

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 414

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 415

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 416

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 417

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 418

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 419

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 420

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 421

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 422

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 423

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 424

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 425

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 426

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 427

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 428

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 429

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 430

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 431

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 432

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 433

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 434

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 435

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 436

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 437

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 438

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 439

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 440

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 441

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 442

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 443

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 444

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 445

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 446

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 447

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 448

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 449

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 450

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 451

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 452

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 453

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 454

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 455

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 456

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 457

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 458

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 459

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 460

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 461

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 462

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 463

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 464

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 465

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 466

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 467

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 468

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 469

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 470

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 471

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 472

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 473

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 474

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 475

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 476

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 477

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 478

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 479

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 480

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 481

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 482

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 483

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 484

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 485

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 486

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 487

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 488

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 489

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 490

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 491

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 492

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 493

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 494

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 495

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 496

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 497

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 498

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 499

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 500

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 501

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 502

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 503

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 504

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 505

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 506

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 507

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 508

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 509

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 510

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 511

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 512

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 513

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 514

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 515

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 516

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 517

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 518

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 519

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 520

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 521

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (15,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 522

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 523

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 524

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 525

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 526

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 527

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 528

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 529

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 530

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (16,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 531

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 532

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 533

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 534

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 535

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 536

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 537

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 538

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 539

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 540

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 541

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 542

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 543

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 544

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 545

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 546

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 547

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 548

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 549

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 550

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 551

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 552

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 553

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 554

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 555

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 556

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 557

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 558

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 559

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 560

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 561

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 562

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 563

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 564

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 565

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 566

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 567

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 568

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 569

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 570

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 571

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 572

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 573

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 574

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 575

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 576

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 577

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 578

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 579

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 580

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 581

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 582

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 583

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 584

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 585

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 586

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 587

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 588

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 589

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 590

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 591

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 592

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 593

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 594

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 595

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (11,25) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 596

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 597

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 598

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 599

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 600

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 601

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 602

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 603

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 604

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 605

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 606

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 607

/tmp/ipykernel_113/4097070489.py:6: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path + '/2024-08-15/dbo.accm_labs.csv', chunksize=chunk_size):

chunk 608

In [18]:
len(myLabsDf['osler_id'].unique())

2858

In [20]:
# myLabsDf.to_csv('labs.csv')

In [26]:
print(myLabsDf.head().to_string())

                               osler_id  order_proc_id  pat_enc_csn_id   proc_id  proc_cat_id sensitive_yn order_type lab_group                          resulting_lab           order_time          result_time authorizing_prov_id  referring_prov_id  specimen_taken_time   specimen_recv_time specimen_type    specimen_source  order_results_line  component_id result_flag order_status result_status    lab_status ord_value  ord_num_value reference_low reference_high reference_unit result_sub_idn                            res_comp_singleline res_comp_multiline result_in_range_yn  lrr_based_organ_id data_type loinc_code    RN
0  05132cab-8d71-4573-9bd8-c0769c9bf491    744127535.0    1.368473e+09  185877.0        110.0            N        Lab       lab  JOHNS HOPKINS MEDICAL LABS (J.H.M.L.)  2022-05-05 16:02:00  2022-05-05 18:17:00               84744            84744.0  2022-05-05 16:51:00  2022-05-05 16:57:00         Blood  Blood, peripheral                   9  1.234000e+09         Low    Completed         Final  Final result        77          77.00           150            350        K/cu mm            NaN  Result double checked. No clot found in tube.                NaN                NaN                 NaN    Number      777-3  1503
1  05132cab-8d71-4573-9bd8-c0769c9bf491    755183841.0    1.368473e+09  185070.0        110.0            N        Lab       lab  JOHNS HOPKINS MEDICAL LABS (J.H.M.L.)  2022-06-13 22:09:00  2022-06-13 22:10:00              401903            78632.0  2022-06-13 20:49:00  2022-06-13 21:00:00         Blood  Blood, peripheral                   2  1.234000e+09         Low    Completed         Final  Final result         1           1.00            24             44              %            NaN                                            NaN                NaN                NaN                 NaN    Number      737-7  1504
2  05132cab-8d71-4573-9bd8-c0769c9bf491    756234529.0    1.368473e+09  185877.0        110.0            N        Lab       lab  JOHNS HOPKINS MEDICAL LABS (J.H.M.L.)  2022-06-17 08:01:00  2022-06-17 12:18:00              103489            78632.0  2022-06-17 11:37:00  2022-06-17 12:01:00         Blood  Blood, peripheral                   9  1.234000e+09         Low    Completed         Final  Final result        67          67.00           150            350        K/cu mm            NaN                         Result double checked.                NaN                NaN                 NaN    Number      777-3  1505
3  05132cab-8d71-4573-9bd8-c0769c9bf491    757554524.0    1.368473e+09  185877.0        110.0            N        Lab       lab  JOHNS HOPKINS MEDICAL LABS (J.H.M.L.)  2022-06-22 08:01:00  2022-06-22 13:24:00              103489            78632.0  2022-06-22 12:10:00  2022-06-22 12:24:00         Blood  Blood, peripheral                   4  1.234000e+09         Low    Completed         Final  Final result      25.5          25.50          41.0           53.0              %            NaN                                            NaN                NaN                NaN                 NaN    Number     4544-3  1506
4  05132cab-8d71-4573-9bd8-c0769c9bf491    743844188.0    1.368473e+09  185070.0        110.0            N        Lab       lab  JOHNS HOPKINS MEDICAL LABS (J.H.M.L.)  2022-05-04 19:18:00  2022-05-04 19:19:00               84744            84744.0  2022-05-04 17:23:00  2022-05-04 17:33:00         Blood  Blood, peripheral                   8  1.234000e+09         Low    Completed         Final  Final result      0.21           0.21          1.10           4.80        K/cu mm            NaN                                            NaN                NaN                NaN                 NaN    Number      731-0  1507

In [171]:
len(myDflow['pat_enc_csn_id'].unique())

17517

In [27]:
myDfHistory = pd.read_csv(file_path + '/2024-08-15/dbo.accm_medical_hx_summary.csv')

,osler_id,medical_hx_date,med_hx_start_dt,med_hx_end_dt,dx_id,dx_name,dx_group,parent_dx_name,icd10_code,icd9_code,annotation,RN
0,000ca106-ec49-42f9-ba07-7ba91a4203ae,NaN,NaN,NaN,102539.0,Ear infection,DISEASES-EAR AND MASTOID PROCESS,Suppurative and unspecified otitis media,H66.90,382.9,NaN,2
1,000ca106-ec49-42f9-ba07-7ba91a4203ae,NaN,NaN,NaN,91271.0,Autism,MENTAL DISORDERS,Pervasive developmental disorders,F84.0,299.00,NaN,3
2,0034728c-8d81-4aab-8e0b-daade67b0e66,4/18/2007,NaN,NaN,94476.0,Eczema,SKIN AND SUBCUTANEOUS TISSUE,Contact dermatitis and other eczema,L30.9,692.9,NaN,4
3,0034728c-8d81-4aab-8e0b-daade67b0e66,2011,2011-01-01,2011-01-01,154232.0,Avascular necrosis of bone,MUSCULOSKELETAL SYSTEM AND CONNECTIVE TISSUE,Other bone/cartilage disease,M87.00,733.40,NaN,5
4,0034728c-8d81-4aab-8e0b-daade67b0e66,04/18/2007,2007-04-18,2007-04-18,94476.0,Eczema,SKIN AND SUBCUTANEOUS TISSUE,Contact dermatitis and other eczema,L30.9,692.9,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...
5772139,fff83d3b-3d84-442d-b260-d5c78729842a,NaN,NaN,NaN,168602.0,ILD (interstitial lung disease),MODEL COMMUNITY ACQUIRED PNEUMONIA GROUP,Postinflammatory pulmonary fibrosis,J84.9,515,NaN,5772141
5772140,fff83d3b-3d84-442d-b260-d5c78729842a,NaN,NaN,NaN,101555.0,Heart attack,CIRCULATORY SYSTEM,Acute myocardial infarction,I21.9,410.90,NaN,5772142
5772141,fff83d3b-3d84-442d-b260-d5c78729842a,NaN,NaN,NaN,286960.0,Retinitis pigmentosa of both eyes,DISORDERS OF THE EYE AND ADNEXA,Retinal disorders NEC,H35.52,362.74,NaN,5772143
5772142,fff83d3b-3d84-442d-b260-d5c78729842a,NaN,NaN,NaN,138118.0,HTN (hypertension),CIRCULATORY SYSTEM,Essential hypertension,I10,401.9,NaN,5772144
5772143,fff83d3b-3d84-442d-b260-d5c78729842a,NaN,NaN,NaN,66850.0,Coronary artery disease,CIRCULATORY SYSTEM,Other forms of chronic ischemic heart disease,I25.10,414.00,NaN,5772145

In [28]:
myDfHistory = myDfHistory[myDfHistory['osler_id'].isin(myIds[0])]

In [30]:
myDfHistory['osler_id'].unique().size

2536

In [31]:
myDfHistory

,osler_id,medical_hx_date,med_hx_start_dt,med_hx_end_dt,dx_id,dx_name,dx_group,parent_dx_name,icd10_code,icd9_code,annotation,RN
326,0338a091-6d6a-411d-b5c6-2c5f03180484,NaN,NaN,NaN,142929.0,Asthma,MODEL COMMUNITY ACQUIRED PNEUMONIA GROUP,Asthma,J45.909,493.90,NaN,328
327,0338a091-6d6a-411d-b5c6-2c5f03180484,NaN,NaN,NaN,90782.0,Anxiety,MENTAL DISORDERS,"Anxiety, dissociative and somatoform disorders",F41.9,300.00,NaN,329
328,0338a091-6d6a-411d-b5c6-2c5f03180484,NaN,NaN,NaN,78949.0,Diabetes mellitus,CYSTIC FIBROSIS,Diabetes mellitus,E11.9,250.00,NaN,330
329,0338a091-6d6a-411d-b5c6-2c5f03180484,NaN,NaN,NaN,139894.0,Sleep apnea,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS",General symptoms,G47.30,780.57,NaN,331
330,0338a091-6d6a-411d-b5c6-2c5f03180484,NaN,NaN,NaN,126092.0,Depression,MENTAL DISORDERS,"Depressive disorder, not elsewhere classified",F32.A,311,NaN,332
...,...,...,...,...,...,...,...,...,...,...,...,...
5771802,fba2c601-c939-4629-86f8-f0c7970c071b,2009,NaN,NaN,101568.0,Myocardial infarction,CIRCULATORY SYSTEM,Acute myocardial infarction,I21.9,410.90,NaN,5771804
5771803,fba2c601-c939-4629-86f8-f0c7970c071b,NaN,NaN,NaN,189565.0,Pacemaker,COMPROMISED,Other postprocedural states,Z95.0,V45.01,NaN,5771805
5771804,fba2c601-c939-4629-86f8-f0c7970c071b,NaN,NaN,NaN,139894.0,Sleep apnea,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS",General symptoms,G47.30,780.57,NaN,5771806
5771805,fba2c601-c939-4629-86f8-f0c7970c071b,NaN,NaN,NaN,66850.0,Coronary artery disease,CIRCULATORY SYSTEM,Other forms of chronic ischemic heart disease,I25.10,414.00,NaN,5771807
5771806,fba2c601-c939-4629-86f8-f0c7970c071b,NaN,NaN,NaN,97293.0,CHF (congestive heart failure),CIRCULATORY SYSTEM,Heart failure,I50.9,428.0,NaN,5771808

In [170]:
myHeader

,osler_id,pat_enc_csn_id,inpatient_data_id,recorded_time,meas_value,meas_comment,meas_id,meas_row_type_c,meas_val_type_c,meas_template_id,meas_fsd_id,meas_line,meas_occurance,rw_meas_id,ip_lda_id,rw_row_type_c,rw_val_type_c,meas_taken_user_id,RN
0,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.155891e+09,18599880.0,2016-03-08 15:59:00,Hand Therapy,NaN,3044010007169,1,8,3044010007167,11348532,44,NaN,NaN,NaN,NaN,NaN,HCOOK1,2

In [242]:
data_dict = {'Temperature(F)': 6, 'Height(In)': 11, 'GCS': 401001, 'Weight(Kg)': 304500800, 'BMI': 301070, 'AGE': 'patients_df = pd.read_csv(data_dir+\'2024-08-15/dbo.accm_patient.csv\')', 'LOWFLOW': '?', 'NOFLOW': '?', 'RANKIN': 3649, 'SEX': 'OTHER DATASET', 'RYTHM': '?', 'TROPO': 'accm_labs?', 'LEUCO': '?', 'arrest time': '?'}
data_dict

{'Temperature(F)': 6,
 'Height(In)': 11,
 'GCS': 401001,
 'Weight(Kg)': 304500800,
 'BMI': 301070,
 'AGE': "patients_df = pd.read_csv(data_dir+'2024-08-15/dbo.accm_patient.csv')",
 'LOWFLOW': '?',
 'NOFLOW': '?',
 'RANKIN': 3649,
 'SEX': 'OTHER DATASET',
 'RYTHM': '?',
 'TROPO': '?',
 'LEUCO': '?'}

In [167]:
myDflow.columns  = myHeader.columns[:len(myHeader.columns)-1]

In [238]:
import matplotlib.pyplot as plt # 6, 17051
myTempFilter = (myDflow['meas_id'] == 1570770459)
# myDflow.loc[myTempFilter, 'meas_value'] = myDflow.loc[myTempFilter, 'meas_value'].astype(float) 
myDflow[myTempFilter].groupby('osler_id').agg({'meas_value': 'min'})
# myDf = myDflow[myTempFilter]#[myDflow['osler_id'] == '75ea9ca3-098f-49f0-81d6-8c3a86d95353'][myDflow['pat_enc_csn_id'] == 1368159186.0]
# plt.scatter(x = myDf['recorded_time'],y = myDf['meas_value'])

Empty DataFrame
Columns: [meas_value]
Index: []

In [ ]:
print(myDf['pat_enc_csn_id'].astype(str).unique())

In [ ]:
myDf['recorded_time'] = pd.to_datetime(myDf['recorded_time'])
print(myDf[myDf['meas_value'] < 96].sort_values('recorded_time').to_string())

In [240]:
print(myDflo[myDflo['flo_meas_name'].str.contains('LEUCO') & ~myDflo['flo_meas_name'].str.contains('RECORD')].groupby('flo_meas_name').agg({'flo_meas_id': 'max'}).sort_values(by='flo_meas_id').to_string())

                                                                            flo_meas_id
flo_meas_name
JHM RX METHOTREXATE AND LEUCOVORIN MONITORING GROUP                              408007
ZZZRETIRED JHM RX METHOTREXATE TDM NAVIGATOR MONITORING LEUCOVORIN REGIMEN       408015
JHM RX METHOTREXATE TDM NAVIGATOR MONITORING LEUCOVORIN REGIMENS                 408024
JHM RX METHOTREXATE TDM NAVIGATOR MONITORING OTHER LEUCOVORIN REGIMENS           408025

In [7]:
data_dir = '/home/idies/workspace/SAFE/'
database_folder = os.path.join(data_dir,'2024-08-15')
os.listdir(database_folder)

FileNotFoundError: [Errno 2] No such file or directory: '/home/idies/workspace/SAFE/2024-08-15'

In [7]:
database_folder_ptsd = os.path.join(data_dir,'ptsd_signal')
os.listdir(database_folder_ptsd)

['core.ptsd_record.csv', 'core.ptsd_signal.csv']

In [9]:
myPtsdRecord = pd.read_csv(database_folder_ptsd + '/core.ptsd_record.csv')

In [10]:
myPtsdRecord.shape

(887649, 17)

In [11]:
myPtsdRecord.head(10)

,record_id,pat_enc_csn_id,device,record_date,inst_id,seq,filename,fmt,loc,start_time,end_time,n_sample,n_signal,rate,chksum,dt,RN
0,1283813,1166851017,HL7M,2016-07-15,NaN,NaN,1166851017-2016-07-15-1-HL7M,feather,icu,2016-07-15 00:00:00,2016-07-15 17:47:00,1086,9,0.016667,da955b382ba91a9ec39689a13e9d3474,2021-12-17 21:56:51.113,2
1,1283822,1167752812,HL7M,2016-07-18,NaN,NaN,1167752812-2016-07-18-1-HL7M,feather,floor,2016-07-18 00:00:00,2016-07-19 00:00:00,1443,6,0.016667,587622aebb3c4bed13624da816f5cf52,2021-12-17 21:57:33.607,3
2,1283815,1167752812,HL7M,2016-07-12,NaN,NaN,1167752812-2016-07-12-1-HL7M,feather,icu,2016-07-12 00:00:00,2016-07-13 00:00:00,1480,14,0.016667,0bb2b279c754f1a9392c26786b3f9eae,2021-12-17 21:57:33.607,4
3,1283819,1167752812,HL7M,2016-07-15,NaN,NaN,1167752812-2016-07-15-1-HL7M,feather,floor,2016-07-15 00:00:00,2016-07-16 00:00:00,1430,6,0.016667,4d9afef3e3efd7895225702cd7ce0c9a,2021-12-17 21:57:33.607,5
4,1283816,1167752812,HL7M,2016-07-13,NaN,NaN,1167752812-2016-07-13-1-HL7M,feather,icu,2016-07-13 00:00:00,2016-07-13 18:46:00,1129,13,0.016667,7c3e9a557855e224317a8e21dee05ccd,2021-12-17 21:57:33.607,6
5,1283820,1167752812,HL7M,2016-07-16,NaN,NaN,1167752812-2016-07-16-1-HL7M,feather,floor,2016-07-16 00:00:00,2016-07-17 00:00:00,1438,6,0.016667,b8387f9b866042f7be652fd3417fd1f2,2021-12-17 21:57:33.607,7
6,1283823,1167752812,HL7M,2016-07-19,NaN,NaN,1167752812-2016-07-19-1-HL7M,feather,floor,2016-07-19 00:00:00,2016-07-20 00:00:00,1428,6,0.016667,2c37509478d7132a62eb57ec612a1cb1,2021-12-17 21:57:33.607,8
7,1283817,1167752812,HL7M,2016-07-13,NaN,NaN,1167752812-2016-07-13-2-HL7M,feather,floor,2016-07-13 18:46:00,2016-07-14 00:00:00,304,6,0.016667,df56883a3697ed7e38a381b7c507bd43,2021-12-17 21:57:33.607,9
8,1283818,1167752812,HL7M,2016-07-14,NaN,NaN,1167752812-2016-07-14-1-HL7M,feather,floor,2016-07-14 00:00:00,2016-07-15 00:00:00,1408,6,0.016667,7d9b18c236cb5ef6095a7e5c937b155b,2021-12-17 21:57:33.607,10
9,1283821,1167752812,HL7M,2016-07-17,NaN,NaN,1167752812-2016-07-17-1-HL7M,feather,floor,2016-07-17 00:00:00,2016-07-18 00:00:00,1416,6,0.016667,6def06fed055548072ad5973d5f9144b,2021-12-17 21:57:33.607,11

In [31]:
myPtsdSignal = pd.read_csv(database_folder_ptsd + '/core.ptsd_signal.csv')

/tmp/ipykernel_386/3889951460.py:1: DtypeWarning: Columns (4,8) have mixed types. Specify dtype option on import or set low_memory=False.
  myPtsdSignal = pd.read_csv(database_folder_ptsd + '/core.ptsd_signal.csv')

In [32]:
myPtsdSignal = myPtsdSignal[myPtsdSignal['signal'] == 'Temp']

In [33]:
myColsToUse = list(myPtsdRecord.columns.difference(myPtsdSignal.columns))
myColsToUse.append('record_id')

In [34]:
myPtsdSignal = myPtsdSignal.merge(myPtsdRecord[myColsToUse], on=['record_id'])

In [35]:
myPtsdSignal

,record_id,pat_enc_csn_id,device,signal,metric,record_date,inst_id,seq,loc,start_time,end_time,n_sample,rate,dt,RN,chksum,filename,fmt,n_signal
0,1001315.0,1266258858,TSDB,Temp,NaN,2019-02-21,NaN,NaN,or,2019-02-21 07:30:00,2019-02-21 15:39:00,245,0.016667,2021-09-02 13:51:28.810,768752,0cb6e6b09926adce9f57a95dcb17d106,1266258858-2019-02-21-1-TSDB,feather,28
1,1005798.0,1266598376,TSDB,Temp,NaN,2019-06-04,NaN,NaN,or,2019-06-04 05:41:00,2019-06-04 17:09:00,431,0.016667,2021-09-03 21:58:34.743,790778,fb3dc0028c9667ac6fac2531734d1758,1266598376-2019-06-04-1-TSDB,feather,21
2,1190541.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-12,NaN,NaN,icu,2019-02-12 00:00:00,2019-02-13 00:00:00,1441,0.016667,2021-10-27 11:03:58.347,898325,44324f70736e41b8e3d17c4d3f956067,1268829626-2019-02-12-1-TSDB,feather,13
3,1190531.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-02,NaN,NaN,icu,2019-02-02 00:00:00,2019-02-03 00:00:00,1440,0.016667,2021-10-27 11:03:58.347,898990,a06fdd6bddab83bc5e07c46747dbb4ca,1268829626-2019-02-02-1-TSDB,feather,15
4,1190540.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-11,NaN,NaN,icu,2019-02-11 00:00:00,2019-02-12 00:00:00,1440,0.016667,2021-10-27 11:03:58.347,898991,38929073b9e15cd2a2c2e34180412dcb,1268829626-2019-02-11-1-TSDB,feather,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43443,1481159.0,1341223921,TSDB,Temp,t.oru.u.13.m.2932,2021-07-23,NaN,NaN,icu,2021-07-23 00:00:00.000,2021-07-24 00:00:00.000,402,0.016667,2022-09-23 07:00:22.103,10084186,df6cc3fbab1e3e22c16151a0c5453ad6,1341223921-2021-07-23-1-TSDB,feather,15
43444,1479595.0,1341313343,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 18:53:00.000,2021-07-23 00:00:00.000,307,0.016667,2022-09-23 03:55:44.463,10085186,d5533bfc41241c3e4c6aa7f71335e492,1341313343-2021-07-22-3-TSDB,feather,19
43445,1479596.0,1341313343,TSDB,Temp,t.oru.u.13.m.2932,2021-07-23,NaN,NaN,icu,2021-07-23 00:00:00.000,2021-07-24 00:00:00.000,401,0.016667,2022-09-23 03:55:44.463,10085205,bc19de82777b80c4e62c41943b8da90b,1341313343-2021-07-23-1-TSDB,feather,16
43446,1563764.0,1341314854,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 06:39:00.000,2021-07-23 00:00:00.000,992,0.016667,2022-09-26 13:42:36.840,10085231,83eecd94f9f04e98027f7c6f9775fbdf,1341314854-2021-07-22-2-TSDB,feather,9
43447,1477665.0,1341391945,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 18:22:00.000,2021-07-23 00:00:00.000,331,0.016667,2022-09-22 23:40:40.503,10085468,1a772c1984931cd22dd1037f9a78c0f9,1341391945-2021-07-22-1-TSDB,feather,19

In [36]:
del myPtsdRecord

In [38]:
myPtsdSignal = myPtsdSignal[myPtsdSignal['loc'] == 'icu']

In [39]:
myPtsdSignal

,record_id,pat_enc_csn_id,device,signal,metric,record_date,inst_id,seq,loc,start_time,end_time,n_sample,rate,dt,RN,chksum,filename,fmt,n_signal
2,1190541.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-12,NaN,NaN,icu,2019-02-12 00:00:00,2019-02-13 00:00:00,1441,0.016667,2021-10-27 11:03:58.347,898325,44324f70736e41b8e3d17c4d3f956067,1268829626-2019-02-12-1-TSDB,feather,13
3,1190531.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-02,NaN,NaN,icu,2019-02-02 00:00:00,2019-02-03 00:00:00,1440,0.016667,2021-10-27 11:03:58.347,898990,a06fdd6bddab83bc5e07c46747dbb4ca,1268829626-2019-02-02-1-TSDB,feather,15
4,1190540.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-02-11,NaN,NaN,icu,2019-02-11 00:00:00,2019-02-12 00:00:00,1440,0.016667,2021-10-27 11:03:58.347,898991,38929073b9e15cd2a2c2e34180412dcb,1268829626-2019-02-11-1-TSDB,feather,13
5,1190510.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-01-14,NaN,NaN,icu,2019-01-14 00:00:00,2019-01-15 00:00:00,1440,0.016667,2021-10-27 11:03:58.347,899547,269d09cd006b4394735bb443938a82bb,1268829626-2019-01-14-1-TSDB,feather,12
6,1190512.0,1268829626,TSDB,Temp,t.oru.u.13.m.2932,2019-01-16,NaN,NaN,icu,2019-01-16 00:00:00,2019-01-17 00:00:00,1437,0.016667,2021-10-27 11:03:58.347,899954,9cd99c82eba0ea96b33eb648f199d2e5,1268829626-2019-01-16-1-TSDB,feather,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43443,1481159.0,1341223921,TSDB,Temp,t.oru.u.13.m.2932,2021-07-23,NaN,NaN,icu,2021-07-23 00:00:00.000,2021-07-24 00:00:00.000,402,0.016667,2022-09-23 07:00:22.103,10084186,df6cc3fbab1e3e22c16151a0c5453ad6,1341223921-2021-07-23-1-TSDB,feather,15
43444,1479595.0,1341313343,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 18:53:00.000,2021-07-23 00:00:00.000,307,0.016667,2022-09-23 03:55:44.463,10085186,d5533bfc41241c3e4c6aa7f71335e492,1341313343-2021-07-22-3-TSDB,feather,19
43445,1479596.0,1341313343,TSDB,Temp,t.oru.u.13.m.2932,2021-07-23,NaN,NaN,icu,2021-07-23 00:00:00.000,2021-07-24 00:00:00.000,401,0.016667,2022-09-23 03:55:44.463,10085205,bc19de82777b80c4e62c41943b8da90b,1341313343-2021-07-23-1-TSDB,feather,16
43446,1563764.0,1341314854,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 06:39:00.000,2021-07-23 00:00:00.000,992,0.016667,2022-09-26 13:42:36.840,10085231,83eecd94f9f04e98027f7c6f9775fbdf,1341314854-2021-07-22-2-TSDB,feather,9
43447,1477665.0,1341391945,TSDB,Temp,t.oru.u.13.m.2932,2021-07-22,NaN,NaN,icu,2021-07-22 18:22:00.000,2021-07-23 00:00:00.000,331,0.016667,2022-09-22 23:40:40.503,10085468,1a772c1984931cd22dd1037f9a78c0f9,1341391945-2021-07-22-1-TSDB,feather,19

In [44]:
file_path = database_folder+'/dbo.accm_flowsheet.csv'
chunk_size = 1e6

# icu_ca_patients_enc_csn_ids = icu_ca_patients_df['pat_enc_csn_id']
flowsheet_chunks = []

num_chunks = 0
for chunk in pd.read_csv(file_path, chunksize=chunk_size):
    # filtered_chunk = chunk[chunk['pat_enc_csn_id'].isin(icu_ca_patients_enc_csn_ids)]
    flowsheet_chunks.append(chunk)
    num_chunks += 1
    print(f'Chunk {num_chunks} Processed.')
    break

flowsheet_df = pd.concat(flowsheet_chunks, ignore_index=True)
flowsheet_df.head()

Chunk 1 Processed.

,osler_id,pat_enc_csn_id,inpatient_data_id,recorded_time,meas_value,meas_comment,meas_id,meas_row_type_c,meas_val_type_c,meas_template_id,meas_fsd_id,meas_line,meas_occurance,rw_meas_id,ip_lda_id,rw_row_type_c,rw_val_type_c,meas_taken_user_id,RN
0,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.155891e+09,18599880.0,2016-03-08 15:59:00,Hand Therapy,NaN,3044010007169,1,8,3044010007167,11348532,44,NaN,NaN,NaN,NaN,NaN,HCOOK1,2
1,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.325504e+09,69472630.0,2021-04-22 08:47:00,81.02,NaN,28032,3,1,43,40048074,20,NaN,NaN,NaN,NaN,NaN,AGIBSO31,3
2,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.343643e+09,81091500.0,2021-08-24 00:02:00,32220,NaN,701,1,10,304001009,42340258,10,148.0,304610.0,6129594.0,7.0,NaN,CBURNS25,4
3,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.402979e+09,115370662.0,2023-08-14 09:48:00,1,NaN,37594,3,1,43,58512003,38,NaN,NaN,NaN,NaN,NaN,MYCHARTPTG,5
4,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.343643e+09,81091500.0,2021-10-15 08:11:00,17,NaN,139000106,3,1,43,43349353,97,NaN,NaN,NaN,NaN,NaN,CBURNS25,6

In [48]:
print(flowsheet_df[flowsheet_df['meas_comment'].str.contains('emp')].groupby('meas_comment').agg({'meas_comment': 'count'}).to_string())

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [49]:
flowsheet_df['meas_comment'].str.contains('emp')

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
999995    NaN
999996    NaN
999997    NaN
999998    NaN
999999    NaN
Name: meas_comment, Length: 1000000, dtype: object

In [53]:
file_path = database_folder+'/dbo.accm_flowsheet_rows_name.csv'
myDf = pd.read_csv(file_path)

In [67]:
myDf[myDf['rw_row_name'].str.contains('emperature')]

,osler_id,pat_enc_csn_id,inpatient_data_id,rw_row_name,meas_occurance,rw_meas_id,ip_lda_id,ipds_template_id,RN
408,0e0bf3d1-fea5-43be-951a-36b11027b366,1.441653e+09,140296132.0,Urinary Catheter (Adult) Temperature probe 16 Fr,1017,7085610,9268465.0,3.044010e+10,410
7059,03526666-68fd-4c1a-ad47-8ea9cc075592,1.078519e+09,16319875.0,[REMOVED] Urinary Catheter Temperature probe 1...,189,7085610,760003.0,1.430000e+02,7061
7588,0a1d9af4-1207-4e5d-9f8e-baad4014bc2d,1.175768e+09,21036646.0,[REMOVED] Urinary Catheter Temperature probe 1...,98,7085610,1305001.0,3.100000e+04,7590
8047,04f58365-0a05-4399-812c-ece35998b2f1,1.378128e+09,99161913.0,Urinary Catheter Temperature probe 16 Fr,392,7085610,7028928.0,NaN,8049
8187,0e1caa8c-eb90-4fb4-aa91-7f036665cdfd,1.136952e+09,17590274.0,[REMOVED] Urinary Catheter Temperature probe 1...,291,7085610,869287.0,3.106000e+04,8189
...,...,...,...,...,...,...,...,...,...
8062168,f60379a1-f893-4aca-b0e0-5b98dde16b2b,1.042633e+09,6143223.0,[REMOVED] Urinary Catheter Temperature probe 1...,348,7085610,8649.0,3.010100e+04,8062170
8062388,fb8eb07e-9c96-4a63-9a21-5c30b382e074,1.178314e+09,21396226.0,[REMOVED] Urinary Catheter Temperature probe 1...,141,7085610,1333236.0,3.041430e+05,8062390
8063055,5839bb16-a83d-46f9-9934-4d8491b0fa67,1.235835e+09,23759060.0,[REMOVED] Urinary Catheter Temperature probe 1...,820,7085610,1647026.0,3.045040e+07,8063057
8068689,d542fcb9-a116-49e0-ad89-dbc55995afb0,1.086958e+09,16740845.0,[REMOVED] Urinary Catheter Temperature probe 1...,228,7085610,792514.0,3.040010e+09,8068691
8068706,d5c8e425-a9d6-4ea8-8bd0-09263f6c6aee,1.061444e+09,11515017.0,Urinary Catheter Temperature probe 16 Fr,1064,7085610,353947.0,3.101000e+04,8068708

In [73]:
flowsheet_df[flowsheet_df['meas_id'] == 7085610]

Empty DataFrame
Columns: [osler_id, pat_enc_csn_id, inpatient_data_id, recorded_time, meas_value, meas_comment, meas_id, meas_row_type_c, meas_val_type_c, meas_template_id, meas_fsd_id, meas_line, meas_occurance, rw_meas_id, ip_lda_id, rw_row_type_c, rw_val_type_c, meas_taken_user_id, RN]
Index: []

In [74]:
flowsheet_df[flowsheet_df['meas_comment'].str.contains('temp', case=False, na=False)]

,osler_id,pat_enc_csn_id,inpatient_data_id,recorded_time,meas_value,meas_comment,meas_id,meas_row_type_c,meas_val_type_c,meas_template_id,meas_fsd_id,meas_line,meas_occurance,rw_meas_id,ip_lda_id,rw_row_type_c,rw_val_type_c,meas_taken_user_id,RN
58210,0917ad6e-6f1d-46fb-8860-e2ddbc5bdee8,1.388928e+09,105934989.0,2022-12-31 05:15:00,NaN,attempt,304330,1,1,31040,52728028,78,NaN,NaN,NaN,NaN,NaN,DLEIB1,58212
191992,06c7c6ec-3de7-4b0e-b518-5402b881f8b1,1.306922e+09,57463714.0,2020-03-24 13:00:00,5,patient is guarding his lower abdomen when att...,30430556001,1,8,30440102200,31888791,207,NaN,NaN,NaN,NaN,NaN,MBENITE2,191994
216252,00f93fb7-7830-4c06-85f4-12aab30be76e,1.286818e+09,43829560.0,2019-04-01 12:20:00,X,temp >100 Saturday per mom,12684,1,8,796,26581435,52,NaN,NaN,NaN,NaN,NaN,LNAGY2,216254
239163,114c1b94-4f58-4cfe-b610-04d9904229b7,1.389949e+09,106580860.0,2023-01-02 06:24:00,4,axillary temp taken due to pt being warm despi...,7,1,3,33070,52738536,227,NaN,NaN,NaN,NaN,NaN,JVANSLY1,239165
243201,10c277c8-0119-4bab-8e46-817d6c1097d5,1.336080e+09,76155160.0,2021-05-06 15:29:00,Other (Comment),temp 38.3,7096310,1,8,33070,40332242,521,NaN,NaN,NaN,NaN,NaN,KSOKOL1,243203
314759,17b8ef16-dd7a-4f9d-bf3f-3f168212e78b,1.433393e+09,135091460.0,2024-04-18 15:07:00,X,right temple surgical incisioin,3040103830,1,8,1078880001,65119958,353,NaN,NaN,NaN,NaN,NaN,ERAKITI1,314761
348517,0a2409ee-3f0e-4d82-97c6-e0f60a01d701,1.431709e+09,134013407.0,2024-04-11 08:38:00,No,ATTEMPTS BUT DOES NOT GET DAILY,16152,1,8,595,64923202,52,NaN,NaN,NaN,NaN,NaN,BTIDEY1,348519
355799,17b8ef16-dd7a-4f9d-bf3f-3f168212e78b,1.433393e+09,135091460.0,2024-04-18 15:25:00,X,r. temple surgical site,3040103830,1,8,1078880001,65119958,447,NaN,NaN,NaN,NaN,NaN,ERAKITI1,355801
366707,0c03fe46-2802-4cdb-b0e4-a55f1b0297cb,1.337923e+09,77428867.0,2021-06-03 01:16:00,X,Pt reports having a temperature as as as 102F PTA,3040103827,1,8,160014300,40869353,111,NaN,NaN,NaN,NaN,NaN,SDANIE32,366709
407645,006d2483-2bcf-4f95-b9c5-d9dcda478642,1.385078e+09,103459964.0,2022-11-09 20:07:00,96.4,Infant out of isolette being held swaddled in ...,6,1,7,3040010112,51463934,1205,NaN,NaN,NaN,NaN,NaN,KCOLBUR1,407647
424535,1193af31-0253-462d-81cf-e97616d9cd1e,1.334729e+09,75220610.0,2021-04-19 00:00:00,Other (comment),several attempt-3,7073530,1,8,304901000,39969309,67,61.0,3.046100e+05,5613229.0,7.0,NaN,VVARVAR1,424537
426306,0b988bed-df21-430d-9a70-e536a6e32e92,1.280348e+09,40567010.0,2019-01-01 05:15:00,Other (Comment),temp and bleeding,7096310,1,8,30412116,25260289,262,NaN,NaN,NaN,NaN,NaN,NHARRI14,426308
463843,0b988bed-df21-430d-9a70-e536a6e32e92,1.280348e+09,40567010.0,2019-01-01 00:17:00,Other (Comment),temp,7096310,1,8,1020010004,25260289,81,NaN,NaN,NaN,NaN,NaN,ALEWIS92,463845
468504,116634b4-3245-4b6d-8a24-9d980ea6728b,1.349066e+09,84591393.0,2021-11-03 14:36:00,NaN,no temp,7085950,1,3,1600010000,43718125,75,NaN,NaN,NaN,NaN,NaN,HGAW1,468506
475789,016d844e-253c-486d-88ca-4888263fa02d,1.345086e+09,82044284.0,2021-09-15 02:45:00,Off,Temp increased. Bair Hugger turned off.,1120100026,1,8,1120010001,42739451,4573,NaN,NaN,NaN,NaN,NaN,SOLOMUK1,475791
490510,0b988bed-df21-430d-9a70-e536a6e32e92,1.280348e+09,40567010.0,2018-12-31 23:20:00,Other (Comment),temp,7096310,1,8,12000,25253165,1351,NaN,NaN,NaN,NaN,NaN,ALEWIS92,490512
492917,04854223-209a-4a58-afa0-0c41acb55037,1.361567e+09,88519678.0,2022-02-16 10:12:00,NaN,RN was informed at 10:12 am that the patient h...,6,1,7,31000,45544576,20,NaN,NaN,NaN,NaN,NaN,VHAMILT6,492919
508810,11498480-254b-42de-b583-5573f68236a6,1.369732e+09,93898323.0,2022-05-21 12:00:00,Agitated;Combative;Other (Comment),attempts to be combative with pt; tries to hit...,30440105905,1,8,30414300,47327035,682,NaN,NaN,NaN,NaN,NaN,DCHENG30,508812
523777,1827dcef-112c-4abe-8360-36c9c994e345,1.305923e+09,56788128.0,2020-03-04 12:26:00,Pain;Light sensitivity;Other (Comment),"Pt. reports severe L temporal/postocular pain,",3047000037,1,8,16005500200,31644813,56,NaN,NaN,NaN,NaN,NaN,BLUCAS8,523779
603893,016d844e-253c-486d-88ca-4888263fa02d,1.345086e+09,82044284.0,2021-09-15 02:51:00,Off,Temp increased. Bair Hugger turned off.,1120100026,1,8,1120010001,42739451,4579,NaN,NaN,NaN,NaN,NaN,SOLOMUK1,603895
612163,09265317-c4a6-4443-bcae-322c42c77311,1.284436e+09,42081329.0,2019-03-01 11:21:00,Level 2 (3-4xs per wk),attempt 3/1,1123048794,1,8,1123048790,26119009,167,NaN,NaN,NaN,NaN,NaN,JSELTZE5,612165
715614,016d844e-253c-486d-88ca-4888263fa02d,1.345086e+09,82044284.0,2021-09-15 02:30:00,Off,Temp increased. Bair Hugger turned off.,1120100026,1,8,1120010001,42739451,4101,NaN,NaN,NaN,NaN,NaN,SOLOMUK1,715616
725937,075dd2be-ed4b-4e84-b4ee-b7f3261c2edc,1.316365e+09,63177105.0,2020-01-21 12:59:00,98.4,Temperature Oral,6,1,7,31000,35616526,19,NaN,NaN,NaN,NaN,NaN,EDIACHCNVVITAL,725939
731405,10c277c8-0119-4bab-8e46-817d6c1097d5,1.336080e+09,76155160.0,2021-05-05 00:00:00,2,unsuccessful first attempt with 20 g iv 3 cm b...,7073530,1,8,304901000,40326680,538,1022.0,3.040101e+09,5678665.0,7.0,NaN,TSTURM1,731407
775898,0655d261-1e62-42d6-b752-8a8554c2ffff,1.171269e+09,20369912.0,2017-01-25 11:00:00,Other (Comment),temp,7096310,1,8,31000,15182541,212,NaN,NaN,NaN,NaN,NaN,KSIMMO22,775900
782097,0a3473bf-e6f6-4dc5-9bc7-16b4c500423d,1.396431e+09,110893505.0,2023-03-13 18:09:00,106,Checked oral and axillary temps - no difference,7,1,3,16000501,54611547,23,NaN,NaN,NaN,NaN,NaN,AGRANTM1,782099
841264,0bc5d9a0-97d6-4b44-b478-78d3ffb87c00,1.065586e+09,12805140.0,2015-01-05 16:25:00,NaN,Patient attempted use of transfer tub bench to...,112350380,1,8,11230440107519,7327396,250,NaN,NaN,NaN,NaN,NaN,MBARTO13,841266
842802,006d2483-2bcf-4f95-b9c5-d9dcda478642,1.385078e+09,103459964.0,2022-11-18 23:00:00,Left Leg,"laying on R arm, unable to use L arm - cuff mo...",301300,1,8,3040010112,51725445,2020,NaN,NaN,NaN,NaN,NaN,HHARLAC1,842804
853095,0d821012-3cc9-4d9e-a1d4-dad4973120a2,1.339722e+09,78602191.0,2021-07-05 08:09:00,Unable to assess,INTERMITTENTLY WILL FOLLOW COMMANDS/OPENED MOU...,301880,1,8,30414303,41438631,341,NaN,NaN,NaN,NaN,NaN,JBARE1,853097
864441,10c277c8-0119-4bab-8e46-817d6c1097d5,1.336080e+09,76155160.0,2021-05-06 20:25:00,Intervention,"PRN tylenol given, recheck temp",7096320,1,8,30440104917,40332242,732,NaN,NaN,NaN,NaN,NaN,MCHAVEZ6,864443
950318,147a710e-3d1f-4f9b-a56c-6c94733de1b2,1.189483e+09,22390120.0,2016-11-08 12:40:00,Immediate cough,occurred only when the pt attempted to talk wh...,3044022024,1,8,731,14185360,97,NaN,NaN,NaN,NaN,NaN,GMCKEON1,950320
953325,0bc5d9a0-97d6-4b44-b478-78d3ffb87c00,1.065586e+09,12805140.0,2015-01-05 16:22:00,NaN,"Patient requested elastic shoe laces, then was...",112503370,1,8,11230440107483,7327396,247,NaN,NaN,NaN,NaN,NaN,MBARTO13,953327
969550,04854223-209a-4a58-afa0-0c41acb55037,1.344127e+09,81411445.0,2021-09-17 21:00:00,Tenderness,post multiple attempts at foley insertion,3040103904,1,8,30414303,42790219,935,NaN,NaN,NaN,NaN,NaN,JORLIN1,969552
976360,0bc5d9a0-97d6-4b44-b478-78d3ffb87c00,1.065586e+09,12805140.0,2015-01-09 20:28:00,NaN,Patient attempted car transfer but reported to...,112350400,1,8,11230440107519,7376626,236,NaN,NaN,NaN,NaN,NaN,MBARTO13,976362
992341,18e06ec7-5e5f-415a-a485-a965b431d62e,1.377497e+09,98760472.0,2022-08-19 15:00:00,1,3pm attempt,1071204,1,1,1070517,49403174,3,NaN,NaN,NaN,NaN,NaN,KSANCH14,992343

In [72]:
flowsheet_df[flowsheet_df['meas_id'] == 6]

,osler_id,pat_enc_csn_id,inpatient_data_id,recorded_time,meas_value,meas_comment,meas_id,meas_row_type_c,meas_val_type_c,meas_template_id,meas_fsd_id,meas_line,meas_occurance,rw_meas_id,ip_lda_id,rw_row_type_c,rw_val_type_c,meas_taken_user_id,RN
63,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.386340e+09,104229455.0,2022-12-05 13:39:00,98.6,NaN,6,1,7,20,52115268,7,NaN,NaN,NaN,NaN,NaN,MPOOLE4,65
232,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.402979e+09,115370662.0,2023-08-21 16:02:00,97.5,NaN,6,1,7,20,58708610,14,NaN,NaN,NaN,NaN,NaN,SMERED10,234
256,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.080686e+09,18090582.0,2016-02-03 14:02:00,98.8,NaN,6,1,7,20,10965926,7,NaN,NaN,NaN,NaN,NaN,MMILL127,258
371,0a52ef23-22c1-498c-8c2b-da03e6a1caec,1.141939e+09,17776256.0,2016-01-19 13:36:00,97.9,NaN,6,1,7,1070713015,10810798,275,NaN,NaN,NaN,NaN,NaN,JDEUTSC3,373
457,090acb5a-99a4-4889-91cc-d3411c52b5a3,1.304079e+09,55780145.0,2020-02-12 17:00:00,32,NaN,6,1,7,304440107140,31298249,248,NaN,NaN,NaN,NaN,NaN,YWILLI11,459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999788,0c964652-7530-47e7-9fa8-6c69a540e209,1.291310e+09,46860479.0,2019-06-24 16:30:00,97.7,NaN,6,1,7,30440107144,27830856,172,NaN,NaN,NaN,NaN,NaN,YANNAN1,999790
999881,0c964652-7530-47e7-9fa8-6c69a540e209,1.252159e+09,27247093.0,2017-06-19 02:26:00,98.6,NaN,6,1,7,16000450600,17411960,11,NaN,NaN,NaN,NaN,NaN,PGUMBAN1,999883
999885,0c964652-7530-47e7-9fa8-6c69a540e209,1.252159e+09,27247093.0,2017-06-23 20:09:00,97.9,NaN,6,1,7,31000,17486386,223,NaN,NaN,NaN,NaN,NaN,RTALITE1,999887
999969,08579850-84e4-45ac-8718-381577f5b529,1.429946e+09,132847078.0,2024-03-25 20:29:00,99.1,NaN,6,1,7,31010,64425070,1141,NaN,NaN,NaN,NaN,NaN,CFOWLER9,999971
999994,08579850-84e4-45ac-8718-381577f5b529,1.426040e+09,130300922.0,2024-02-07 04:53:00,99.1,NaN,6,1,7,31010,63111390,52,NaN,NaN,NaN,NaN,NaN,GBROOK19,999996